[package]
name = "chip8"
version = "0.1.0"
authors = ["Pierre Leidbring <pierre.leidbring@gmail.com>"]

[lib]
name = "chip8"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.29"
rand = "*"
lazy_static = "1.2.0"
